# Generated by Django 3.2.2 on 2021-05-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_src', models.CharField(max_length=200)),
                ('colors', models.TextField()),
                ('tags', models.TextField()),
                ('name', models.TextField()),
                ('stars', models.CharField(max_length=50)),
                ('revs', models.CharField(max_length=10)),
                ('price', models.IntegerField()),
                ('og_price', models.CharField(max_length=10)),
            ],
        ),
    ]
