import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="bg-gray-700 p-6">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-6 max-w-sm mx-auto border border-green-200 bg-green-400 rounded-tl-xl drop-shadow-lg filter blur-sm md:blur-0">
        <h1 className="text">This can become a tag</h1>
      </main>
    </div>
  );
}
